### ISSUE TITLE
spot(수상스키장) 좋아요 기능.

### ISSUE THREAD

**Issue by joel-jo-querypie** [g1moon/hello-waterski#11]
- [x] SpotLikes db 만들기 
- [x] GET /spotLike 작업 
- [x] SpotLikeButton 에서 GET/spotLike 를 통해 값 받아오고  isLiked에 따라 좋아요 상태 보여주기. 
- [x] POST /spotLike/like #44 
- [x] POST /spotLike/unLiked 작업 #44 
- [x] like버튼 누르면 like 상태 on/off #44 

# SpotLikes db 만들기.

- id(PK)
- userId
- spotId

# SpotLikes 라우트 만들기.

## 1. `GET /spotLikes`

Response

```
{ spotLikes: [ {id ,userId, spotId}, ... ] } 

```

## 2. `POST /spotLike/like`

- 좋아요 클릭.

Request Params

```
{
 userId: string, //session에서 얻은 userId
 spotId: string, //현재 컴포넌트에서 props로 얻은spotId
}

```

Response

```
{ newId : string } //등록된 ID

```

## 3. `DELETE /spotLike/like`

- 좋아요 해제.

Request Params

```
{
	userId: string, //session에서 얻은 userId
	spotId: string //현재 컴포넌트에서 props로 얻은 spotId
}

```

- Response

```
{ deletedid: string } //삭제된 ID
```

## 4.  `POST /spotLike/isLiked`

SpotLikeButton 컴포넌트에서

- isLiked 상태로 현재 로그인된 유저가 이 spot을 좋아요했는지 확인.
- userId는 session에서 받고, spotId prpos로 받고,
→  **findIndex → 값이 있으면(not -1) → isLiked 상태를 true로 변경**

Request Params

```
{
	userId: string, //session에서 얻은 userId
	spotId: string //현재 컴포넌트에서 props로 얻은 spotId
}

```

- Response

```
{ isLiked: boolean } // 현재 사용자가 이 spot을 좋아하는지.
```
